### ISSUE TITLE
Site identity / Site title is not displayed

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/lc-blank#10]
The "Site Title" is not displayed on browser. [See this screenshot](https://www.evernote.com/l/AjmYwZTKfJVLa76p_SBOyWdJHQtPPXcsfTM).

**Comment by konmavrakis** [comment]
Hey @FoldingTheme check my PR if you want a quick fix :) #11

**Comment by L1lle** [comment]
I'm seeing the same issue. The title is even completely empty when setting a custom page a homepage.

@livecomposer Why don't you merge this fix into the repository and update the theme?

**Comment by ghost** [comment]
Done
