### ISSUE TITLE
Table style in post not showing when create with TinyMCE Advanced

### ISSUE THREAD

**Issue by nevigator** [live-composer/lc-blank#13]
Could you put table-editor in content-element-editor? That will help very much.

Because i don't want to use plugin that need to create and put [shortcode] after, it's waste the time.

And when i create custom css for table, Their style just show the same style in every table even if i put custom HTML style (eg.<table style="width:100%">) in each table element.

I also try to put the class in table element, but it still waste the time.

or if you have any idea please let me know.

Thanks

**Comment by ghost** [comment]
I'm sorry but I'm not sure if I understand your question. Can you create a screenshot or video with your problem?
