### ISSUE TITLE
The Appearance / Menus are not visible anymore

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/lc-blank#7]
https://www.evernote.com/l/AjOPQG1CvHFI3L6cdD0UvGntSTNTFwn5a1U

**Comment by mozalan** [comment]
Hi guys, no update yet?

**Comment by mozalan** [comment]
This prevents anyone using BlankTheme with WordPress version 4.7 - could you please update us on this matter?

**Comment by lumberman** [comment]
Hey guys,
LC Blank never had Menu pre-installed by default. You need to go to WP Admin > LC Settings > Navigation and create a new menu first to have an option to create menu.

We will improve this theme with adding some default menu on install.

**Comment by ghost** [comment]
Done
