### ISSUE TITLE
MENU desappeared from the APPEARENCES

### ISSUE THREAD

**Issue by mozalan** [live-composer/lc-blank#8]
Something is wrong with the theme, could you please check it asap?

Fatal error: Call to undefined function dslc_hf_get_header() in *********/public_html/wp-content/themes/lc-blank/header.php on line 18

**Comment by mozalan** [comment]
13 days and no update at all?... Could you please say something about this problem? No one is able to use Blank Theme with WordPress version 4.7...

**Comment by lumberman** [comment]
Hi there,
I'm sorry for delay answering you. 

This error means you have Live Composer installation damaged. Looks like you have /livecomposer/includes/header-footer.php file missing or damaged. This file contains **function dslc_hf_get_header( $post_ID = false ) {** and it is missing on your install. Did you installed Live Composer via WP-Admin or manually copied files? Try to delete LC in your WP admin and install it via WP Admin. Even if you download it from GitHub it's better to install via WP admin.

To make clear, there is no bug in the theme or LC. It's just a side-effect of broken installation.

**Comment by ghost** [comment]
Hi @mozalan Please, follow the next steps:
1) Try to delete LC in your WP admin and install LC 1.2 via WP Admin.
2) Try to delete LC Blank in your WP admin and install this master branch - https://github.com/live-composer/lc-blank/archive/master.zip
